### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to_html'

### ISSUE THREAD

**Issue by StephenStrand** [AlexArcPy/registrant#11]
Just wanted to say how great this tool is. I'm getting great results with it for the most part, but have two SDE connections where I get the following error and was wondering if anyone had something similar occur and what their fix was? Thanks!

```
AttributeError                            Traceback (most recent call last)
In  [3]:
Line 5:     reporter.gdb2html()

File C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\registrant-0.7-py3.7.egg\registrant\_reporter.py, in gdb2html:
Line 132:   do_report_tables_indexes,

File C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\registrant-0.7-py3.7.egg\registrant\_reporter.py, in _report_tables:
Line 445:   report_path=self.report_file_path)

File C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\registrant-0.7-py3.7.egg\registrant\_build_html.py, in add_div_to_html_page:
Line 86:    html_table = df.to_html(

AttributeError: 'NoneType' object has no attribute 'to_html'
```

**Comment by Asrujit** [comment]
Any solution to this issue or what causes it? Facing the same with sde connection:

> Traceback (most recent call last):
  File "C:\Users\a.sengupta\Desktop\Test32.py", line 3, in <module>
    reporter.gdb2html()
  File "C:\Python27\ArcGISx6410.9\lib\site-packages\registrant\_reporter.py", line 132, in gdb2html
    do_report_tables_indexes,
  File "C:\Python27\ArcGISx6410.9\lib\site-packages\registrant\_reporter.py", line 445, in _report_tables
    report_path=self.report_file_path)
  File "C:\Python27\ArcGISx6410.9\lib\site-packages\registrant\_build_html.py", line 86, in add_div_to_html_page
    html_table = df.to_html(
AttributeError: 'NoneType' object has no attribute 'to_html'
